project_id = "gzsplrzfepezcpfvuiyl"

[functions.ai-project-insights]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.poll-emails]
verify_jwt = false

[functions.ai-field-mapping]
verify_jwt = false
